USE [master]
GO
/****** Object:  Database [TaskManagement_DB]    Script Date: 10-06-2025 19:50:51 ******/
CREATE DATABASE [TaskManagement_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaskManagement_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TaskManagement_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaskManagement_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TaskManagement_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TaskManagement_DB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaskManagement_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TaskManagement_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TaskManagement_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TaskManagement_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TaskManagement_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TaskManagement_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [TaskManagement_DB] SET  MULTI_USER 
GO
ALTER DATABASE [TaskManagement_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TaskManagement_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TaskManagement_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TaskManagement_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TaskManagement_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TaskManagement_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TaskManagement_DB', N'ON'
GO
ALTER DATABASE [TaskManagement_DB] SET QUERY_STORE = ON
GO
ALTER DATABASE [TaskManagement_DB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TaskManagement_DB]
GO
/****** Object:  Table [dbo].[Tasks]    Script Date: 10-06-2025 19:50:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tasks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](250) NULL,
	[Description] [nvarchar](max) NULL,
	[DueDate] [date] NULL,
	[Assignee] [int] NULL,
	[Reviewer] [int] NULL,
	[Status] [nvarchar](50) NULL,
	[Type] [nvarchar](100) NULL,
	[CreatedOnUtc] [datetime2](7) NULL,
	[ModifyOnUtc] [datetime2](7) NULL,
 CONSTRAINT [PK_Tasks] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 10-06-2025 19:50:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Firstname] [nvarchar](100) NULL,
	[Lastname] [nvarchar](100) NULL,
	[CreatedOnUtc] [datetime2](7) NULL,
	[ModifyOnUtc] [datetime2](7) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tasks] ADD  CONSTRAINT [DF_Tasks_Reviewer]  DEFAULT ((0)) FOR [Reviewer]
GO
ALTER TABLE [dbo].[Tasks]  WITH CHECK ADD  CONSTRAINT [FK_Tasks_Users] FOREIGN KEY([Assignee])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[Tasks] CHECK CONSTRAINT [FK_Tasks_Users]
GO
USE [master]
GO
ALTER DATABASE [TaskManagement_DB] SET  READ_WRITE 
GO
